### ISSUE TITLE
Yet another dashboard for Grafana

### ISSUE THREAD

**Issue by j0ju** [pdreker/fritz_exporter#126]
I created yet another dashboard additionally display some data from the host info metrics

[Grafana Dash #17751](https://grafana.com/grafana/dashboards/17751-fritz-exporter-dash/)
(although it is published. Grafana's website currently shows a 404 when searching and clicking it :-/ )

The JSON can be downloaded also [here](https://gist.github.com/j0ju/6f44378e53dedd04549375fe8d6d1ad1).
I attached a screenshot. If you find the link worth to be included in the docs, I would create a PR.
If you have suggestion or find errors please let me know.

![Fritz!Exporter Dash-2022-12-29](https://user-images.githubusercontent.com/7253954/209964252-99885e55-9deb-438a-8443-a81d391d1b93.png)

**Comment by pdreker** [comment]
*Please* make a PR and I'll happily include it. Looks great! The "404 problem" seems to have resolved over night.

Thanks in advance

**Comment by pdreker** [comment]
By the way... I just tried your dashboard and the "Active Hosts" does not work for me. Looking at the expression behind the dashboard it seems to have one of your device names hardcoded.

**Comment by j0ju** [comment]
Thanks for reporting will have a look into it.

**Comment by j0ju** [comment]
Yes I found a panel that was not using the defined $box variable.
An open point: As you cannot update dashboards on the Grafana Dashboards site, for any update or bugfix, you would need to create another dashboard entry on Grafana's site. The same applies to the currently referenced dashboard.
I would suggest adding the dashboard as a file into a repo: either this one or a seperate one?
What do you think?

**Comment by pdreker** [comment]
Err... Yes, you can update the dashboard on grafana.com, I have been doing this  in the past.

Login to grafana.com, go to your dashboard details and under "Revisions" you can upload a new version.

**Comment by j0ju** [comment]
Happy 2023
Thanks for merging and TIL: I found the "Revisions" tab to update dashboards.
