### ISSUE TITLE
Docker image can't be build out of the box

### ISSUE THREAD

**Issue by antiphp** [pdreker/fritz_exporter#139]
Hello, 
I am not a Python developer and without any further knowledge it is not possible to build with the given Docker image, as there are essential files missing. E.g. *.whl, requirements.txt and potentially more.

I am aware of the existing, but 2 year old, Docker image on DockerHub, anyways I would appreciate to utilize the latest version of this tool.

-C

**Comment by antiphp** [comment]
Found I was looking at the wrong DockerHub repo.

**Comment by pdreker** [comment]
Which DockerHub Repo did you look at? If it is an old one of mine, I could delete it to avoid others making the same mistake.

Also build instructions are in the docs at https://fritz-exporter.readthedocs.io/en/latest/building.html

Effectively you just need to run 'poetry build' before the 'docker build command' which will generate the required *.whl file.
