### ISSUE TITLE
Feature idea - Export DSL syncronisations

### ISSUE THREAD

**Issue by manuelmayer-dev** [pdreker/fritz_exporter#289]
**Summary**
Export total dsl synchronisations

**Additional information**
Found on the FritzBox web interface at "internet -> dsl information -> statistics", however I don't know if the TR-064 API and fritzconnection python module supports this.

**Comment by pdreker** [comment]
I am quite sure that I already export all values presented via the API, but I will double check. As an alternative: it should be possible to derive the value from prometheus stats, with the added advantage, that reconnection would be persistent acrosss restart of the Fritz Box. This may require some diving into the prometheus documentation and seeing how one could derive the requested stats using PromQL and a recording rule.

**Comment by pdreker** [comment]
After a more thorough check: the box does not expose this metric via TR-064 and solving this via Prometheus recording rules is stiff proposal, as the metrics that *are* there are not really suitable for computing the value directly.

So unfortunately I will close this as "not planned".
