### ISSUE TITLE
Invalid GMT offset

### ISSUE THREAD

**Issue by robig** [pdreker/fritz_exporter#294]
Hey, promising project. 
Unfotunately I was not able to start it using docker compose.

relevant lines from docker-compose.yml:

> fritz-exporter:
>     image: pdreker/fritz_exporter:2.3.1
>     container_name: fritz-exporter
>     restart: unless-stopped
>     environment:
>       FRITZ_HOSTNAME: '192.168.127.1'
>       FRITZ_USERNAME: 'xxxx'
>       FRITZ_PASSWORD: 'xxxxxx'
>     ports:
>       - "9787:9787"

Docker log:

> fritz-exporter  | RuntimeError: invalid GMT offset
> fritz-exporter  | Traceback (most recent call last):
> fritz-exporter  |   File "<frozen runpy>", line 189, in _run_module_as_main
> fritz-exporter  |   File "<frozen runpy>", line 148, in _get_module_details
> fritz-exporter  |   File "<frozen runpy>", line 112, in _get_module_details
> fritz-exporter  |   File "/usr/local/lib/python3.12/site-packages/fritzexporter/__init__.py", line 1, in <module>
> fritz-exporter  |     from importlib import metadata
> fritz-exporter  |   File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 8, in <module>
> fritz-exporter  |     import zipfile
> fritz-exporter  |   File "/usr/local/lib/python3.12/zipfile/__init__.py", line 14, in <module>
> fritz-exporter  |     import threading
> fritz-exporter  |   File "/usr/local/lib/python3.12/threading.py", line 8, in <module>
> fritz-exporter  |     from time import monotonic as _time
> fritz-exporter  | RuntimeError: invalid GMT offset

**Comment by pdreker** [comment]
That's a weird one: the backtrace is completely outside of the exporter code and happens inside the libraries. What linux distro is this running on (the Docker Host, not the container). Sometimes there are weird interactions between these.

I'll have a look.

**Comment by pdreker** [comment]
Could you check, what "date" on the Docker host produces?  Just to get an idea, how the timezone setup is?

**Comment by pdreker** [comment]
Closed due to no feedback and unreproducible
