### ISSUE TITLE
No Cable Data

### ISSUE THREAD

**Issue by x4FF3** [pdreker/fritz_exporter#62]
hi, 

just started with prometheus and found this exporter :) :+1: 
but unfortunately there is no data about the cable connection of my 6591. would it be possible to get this info?

kr
david

**Comment by pdreker** [comment]
Hi and sorry for the delay, life gets in the way sometimes ;-)

If the box actually delivers the cable data, the exporter can be made to provide it.

I will need some information from the box using some locally installed tools from you. To get this please checkout this repo using git (`git clone https://github.com/pdreker/fritz_exporter.git`) and follow the instruction ion the README.md under "Helping out". You will need fritzconnection installed (`pip install fritzconnection` if not using pipenv).

If you need more help, please ask!

**Comment by 005Zenturio** [comment]
Hi,

fritzconnection -i 192.168.2.1 -s	
	FritzConnection:
version:            0.8.4
model:              FRITZ!Box 6490 Cable (kdg)
Servicenames:
                    WANCommonIFC:1
                    WANDSLLinkC:1
                    WANIPConn:1
                    WANIPv6Firewall:1
                    any:1
()


fritzconnection -i 192.168.2.1 -S WANCommonIFC
FritzConnection:
version:            0.8.4
model:              FRITZ!Box 6490 Cable (kdg)

Servicename:        WANCommonIFC
Actionnames:
                    GetAddonInfos
                    GetCommonLinkProperties
                    GetTotalBytesReceived
                    GetTotalBytesSent
                    GetTotalPacketsReceived
                    GetTotalPacketsSent
                    X_AVM_DE_GetDsliteStatus
                    X_AVM_DE_GetIPTVInfos
fritzconnection -i 192.168.2.1 -S WANDSLLinkC

FritzConnection:
version:            0.8.4
model:              FRITZ!Box 6490 Cable (kdg)

Servicename:        WANDSLLinkC
Actionnames:
                    GetATMEncapsulation
                    GetAutoConfig
                    GetDSLLinkInfo
                    GetDestinationAddress
                    GetFCSPreserved
                    GetModulationType
                    SetATMEncapsulation
                    SetDSLLinkType
                    SetDestinationAddress
                    SetFCSPreserved
()					

fritzconnection -i 192.168.2.1 -S WANIPConn

FritzConnection:
version:            0.8.4
model:              FRITZ!Box 6490 Cable (kdg)

Servicename:        WANIPConn
Actionnames:
                    AddPortMapping
                    DeletePortMapping
                    ForceTermination
                    GetAutoDisconnectTime
                    GetConnectionTypeInfo
                    GetExternalIPAddress
                    GetGenericPortMappingEntry
                    GetIdleDisconnectTime
                    GetNATRSIPStatus
                    GetSpecificPortMappingEntry
                    GetStatusInfo
                    RequestConnection
                    RequestTermination
                    SetConnectionType
                    X_AVM_DE_GetDNSServer
                    X_AVM_DE_GetExternalIPv6Address
                    X_AVM_DE_GetIPv6DNSServer
                    X_AVM_DE_GetIPv6Prefix
()

fritzconnection -i 192.168.2.1 -S WANIPv6Firewall

FritzConnection:
version:            0.8.4
model:              FRITZ!Box 6490 Cable (kdg)

Servicename:        WANIPv6Firewall
Actionnames:
                    AddPinhole
                    CheckPinholeWorking
                    DeletePinhole
                    GetFirewallStatus
                    GetOutboundPinholeTimeout
                    GetPinholePackets
                    UpdatePinhole
()	

 python3 -m fritz_export_helper 192.168.2.1 prometheus '***************' WANIPConn GetConnectionTypeInfo
--------------------------------
RESULT:
{'NewConnectionType': 'IP_Routed', 'NewPossibleConnectionTypes': 'IP_Routed'}
 python3 -m fritz_export_helper 192.168.2.1 prometheus '***************' WANIPConn GetExternalIPAddress
--------------------------------
RESULT:
{'NewExternalIPAddress': 'xx.xxx.xx.xx'}
 python3 -m fritz_export_helper 192.168.2.1 prometheus '***************' WANIPConn GetStatusInfo
--------------------------------
RESULT:
{'NewConnectionStatus': 'Connected',
 'NewLastConnectionError': 'ERROR_NONE',
 'NewUptime': 3226571}
 python3 -m fritz_export_helper 192.168.2.1 prometheus '***************' WANDSLLinkC GetDSLLinkInfo
--------------------------------
RESULT:
{'NewLinkStatus': 'Up', 'NewLinkType': 'PPPoA'}
 python3 -m fritz_export_helper 192.168.2.1 prometheus '***************' WANDSLLinkC GetAutoConfig
--------------------------------
RESULT:
{'NewAutoConfig': False}


please let me know if you need anything else.
Thanks!

**Comment by pdreker** [comment]
Hi,

I know it has been a while, but if you are still willing to help:
I have released 2.2.0 which has a more complete "data donation" feature, which allow you to basically send me the API output of your device (only readable datapoints, private data is sanitized before sending).

So if you have the time could you please check out [the documentation](https://fritz-exporter.readthedocs.io/en/latest/helping_out.html) on sending the data and let me know here, after you have done so.

thanks,
Patrick
