### ISSUE TITLE
monitor dyndns

### ISSUE THREAD

**Issue by ticteam** [pdreker/fritz_exporter#68]
Hello, 
sometime my FritzBox looses the dyndns connection. I'm totally lost, because I cannot reach the box via VPN to do anything. 
Is there a metric to monitor the dyndns ? 

regard Christoph

**Comment by pdreker** [comment]
Unfortunately there is no metric in the box, that I am aware of, which would be suitable.

There might be other options to check connectivity (blackbox exporter tcp/ping check; compare DNS result vs. fritzbox IP address in prometheus rules), but these can get complex rather quickly.
