### ISSUE TITLE
v2.1.0 HostInfo Capability enabled

### ISSUE THREAD

**Issue by ojwer** [pdreker/fritz_exporter#77]
Using the new v2.1.0 docker image I am getting the warning:
_WARNING fritzexporter.fritzdevice | HostInfo Capability enabled on device fritz.box. This may consume a lot of resources!_.
The request is taking more than 10 seconds. Going back to v2.0.0 is solving that problem.
Any hints, what I am doing wrong?

**Comment by pdreker** [comment]
Nothing it seems ;-)

I had accidentally botched the logic for the HostInfo functionality, when using the config via environment variables, which lead to HostInfo being always enabled, which in turn causes the extremely long requests. The warning in the log is there to warn about exactly this, so it did what it is supposed to do ;-)

Anyways: I have just merged v2.1.1. The build pipelines are currently running so in 10-15 minutes there should be a fixed version 2.1.1.

Sorry for the inconvenience. :-)
